version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5433:5433'
  web:
    build: .

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '8000:8000'

    depends_on:
      - db
volumes:
  postgresql-data:
    driver: local
